In [1]:
from scipy.signal import convolve2d

In [2]:
import numpy as np
x = np.zeros((5, 5))

In [3]:
x[2][1] = 100
x[3][2] = 50
x

array([[   0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [   0.,  100.,    0.,    0.,    0.],
       [   0.,    0.,   50.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.]])

In [4]:
k = np.ones((3, 3))
k

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
convolve2d(x, k, mode="valid")

array([[ 100.,  100.,    0.],
       [ 150.,  150.,   50.],
       [ 150.,  150.,   50.]])

In [6]:
k[0][0] = -3
k

array([[-3.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
def relu(z):
    return np.maximum(z, 0)

In [8]:
relu(k)

array([[ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [11]:
a + b

array([5, 7, 9])

In [12]:
out_d = 3
k = 5
w = np.zeros((5, out_d, out_d))
w

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [13]:
for i in range(k):
    w[i][0][0] = 20
    w[i][1][1] = 50
w

array([[[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]]])

In [14]:
mul = np.array([1,2,3,4,5])
mul

array([1, 2, 3, 4, 5])

In [15]:
w.shape

(5, 3, 3)

In [16]:
mul.reshape((5, 1, 1))

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [17]:
tmp = np.multiply(mul.reshape((5, 1, 1)), w)
tmp

array([[[  20.,    0.,    0.],
        [   0.,   50.,    0.],
        [   0.,    0.,    0.]],

       [[  40.,    0.,    0.],
        [   0.,  100.,    0.],
        [   0.,    0.,    0.]],

       [[  60.,    0.,    0.],
        [   0.,  150.,    0.],
        [   0.,    0.,    0.]],

       [[  80.,    0.,    0.],
        [   0.,  200.,    0.],
        [   0.,    0.,    0.]],

       [[ 100.,    0.,    0.],
        [   0.,  250.,    0.],
        [   0.,    0.,    0.]]])

In [18]:
tmp.sum(axis=0)

array([[ 300.,    0.,    0.],
       [   0.,  750.,    0.],
       [   0.,    0.,    0.]])

In [19]:
np.sum(tmp)

1050.0

In [21]:
w = tmp
w

array([[[  20.,    0.,    0.],
        [   0.,   50.,    0.],
        [   0.,    0.,    0.]],

       [[  40.,    0.,    0.],
        [   0.,  100.,    0.],
        [   0.,    0.,    0.]],

       [[  60.,    0.,    0.],
        [   0.,  150.,    0.],
        [   0.,    0.,    0.]],

       [[  80.,    0.,    0.],
        [   0.,  200.,    0.],
        [   0.,    0.,    0.]],

       [[ 100.,    0.,    0.],
        [   0.,  250.,    0.],
        [   0.,    0.,    0.]]])

In [22]:
w.shape

(5, 3, 3)

In [49]:
h = np.zeros((3, 3,))
h[1][2] = 5
h[2][1] = 10
h[0][0] = 3
h[1][1] = 4
h

array([[  3.,   0.,   0.],
       [  0.,   4.,   5.],
       [  0.,  10.,   0.]])

In [50]:
np.multiply(w, h)

array([[[   60.,     0.,     0.],
        [    0.,   200.,     0.],
        [    0.,     0.,     0.]],

       [[  120.,     0.,     0.],
        [    0.,   400.,     0.],
        [    0.,     0.,     0.]],

       [[  180.,     0.,     0.],
        [    0.,   600.,     0.],
        [    0.,     0.,     0.]],

       [[  240.,     0.,     0.],
        [    0.,   800.,     0.],
        [    0.,     0.,     0.]],

       [[  300.,     0.,     0.],
        [    0.,  1000.,     0.],
        [    0.,     0.,     0.]]])

In [51]:
np.multiply(w[4], h)

array([[  300.,     0.,     0.],
       [    0.,  1000.,     0.],
       [    0.,     0.,     0.]])

In [52]:
np.sum(np.multiply(w, h), axis=(1,2))

array([  260.,   520.,   780.,  1040.,  1300.])