In [1]:
from scipy.signal import convolve2d

In [3]:
import numpy as np
x = np.zeros((5, 5))

In [11]:
x[2][1] = 100
x[3][2] = 50
x

array([[   0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [   0.,  100.,    0.,    0.,    0.],
       [   0.,    0.,   50.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.]])

In [12]:
k = np.ones((3, 3))
k

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
convolve2d(x, k, mode="valid")

array([[ 100.,  100.,    0.],
       [ 150.,  150.,   50.],
       [ 150.,  150.,   50.]])

In [14]:
k[0][0] = -3
k

array([[-3.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
def relu(z):
    return np.maximum(z, 0)

In [16]:
relu(k)

array([[ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [19]:
a + b

array([5, 7, 9])

In [21]:
out_d = 3
k = 5
w = np.zeros((5, out_d, out_d))
w

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [22]:
for i in range(k):
    w[i][0][0] = 20
    w[i][1][1] = 50
w

array([[[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]]])

In [23]:
mul = np.array([1,2,3,4,5])
mul

array([1, 2, 3, 4, 5])

In [24]:
w.shape

(5, 3, 3)

In [26]:
mul.reshape((5, 1, 1))

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [28]:
tmp = np.multiply(mul.reshape((5, 1, 1)), w)
tmp

array([[[  20.,    0.,    0.],
        [   0.,   50.,    0.],
        [   0.,    0.,    0.]],

       [[  40.,    0.,    0.],
        [   0.,  100.,    0.],
        [   0.,    0.,    0.]],

       [[  60.,    0.,    0.],
        [   0.,  150.,    0.],
        [   0.,    0.,    0.]],

       [[  80.,    0.,    0.],
        [   0.,  200.,    0.],
        [   0.,    0.,    0.]],

       [[ 100.,    0.,    0.],
        [   0.,  250.,    0.],
        [   0.,    0.,    0.]]])

In [30]:
tmp.sum(axis=0)

array([[ 300.,    0.,    0.],
       [   0.,  750.,    0.],
       [   0.,    0.,    0.]])

In [32]:
np.sum(tmp)

1050.0