In [1]:
from scipy.signal import convolve2d

In [2]:
import numpy as np
x = np.zeros((5, 5))

In [3]:
x[2][1] = 100
x[3][2] = 50
x

array([[   0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [   0.,  100.,    0.,    0.,    0.],
       [   0.,    0.,   50.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.]])

In [4]:
k = np.ones((3, 3))
k

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
convolve2d(x, k, mode="valid")

array([[ 100.,  100.,    0.],
       [ 150.,  150.,   50.],
       [ 150.,  150.,   50.]])

In [6]:
k[0][0] = -3
k

array([[-3.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
def relu(z):
    return np.maximum(z, 0)

In [8]:
relu(k)

array([[ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [11]:
a + b

array([5, 7, 9])

In [12]:
out_d = 3
k = 5
w = np.zeros((5, out_d, out_d))
w

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [13]:
for i in range(k):
    w[i][0][0] = 20
    w[i][1][1] = 50
w

array([[[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]],

       [[ 20.,   0.,   0.],
        [  0.,  50.,   0.],
        [  0.,   0.,   0.]]])

In [14]:
mul = np.array([1,2,3,4,5])
mul

array([1, 2, 3, 4, 5])

In [15]:
w.shape

(5, 3, 3)

In [16]:
mul.reshape((5, 1, 1))

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [17]:
tmp = np.multiply(mul.reshape((5, 1, 1)), w)
tmp

array([[[  20.,    0.,    0.],
        [   0.,   50.,    0.],
        [   0.,    0.,    0.]],

       [[  40.,    0.,    0.],
        [   0.,  100.,    0.],
        [   0.,    0.,    0.]],

       [[  60.,    0.,    0.],
        [   0.,  150.,    0.],
        [   0.,    0.,    0.]],

       [[  80.,    0.,    0.],
        [   0.,  200.,    0.],
        [   0.,    0.,    0.]],

       [[ 100.,    0.,    0.],
        [   0.,  250.,    0.],
        [   0.,    0.,    0.]]])

In [18]:
tmp.sum(axis=0)

array([[ 300.,    0.,    0.],
       [   0.,  750.,    0.],
       [   0.,    0.,    0.]])

In [19]:
np.sum(tmp)

1050.0

In [21]:
w = tmp
w

array([[[  20.,    0.,    0.],
        [   0.,   50.,    0.],
        [   0.,    0.,    0.]],

       [[  40.,    0.,    0.],
        [   0.,  100.,    0.],
        [   0.,    0.,    0.]],

       [[  60.,    0.,    0.],
        [   0.,  150.,    0.],
        [   0.,    0.,    0.]],

       [[  80.,    0.,    0.],
        [   0.,  200.,    0.],
        [   0.,    0.,    0.]],

       [[ 100.,    0.,    0.],
        [   0.,  250.,    0.],
        [   0.,    0.,    0.]]])

In [22]:
w.shape

(5, 3, 3)

In [49]:
h = np.zeros((3, 3,))
h[1][2] = 5
h[2][1] = 10
h[0][0] = 3
h[1][1] = 4
h

array([[  3.,   0.,   0.],
       [  0.,   4.,   5.],
       [  0.,  10.,   0.]])

In [50]:
np.multiply(w, h)

array([[[   60.,     0.,     0.],
        [    0.,   200.,     0.],
        [    0.,     0.,     0.]],

       [[  120.,     0.,     0.],
        [    0.,   400.,     0.],
        [    0.,     0.,     0.]],

       [[  180.,     0.,     0.],
        [    0.,   600.,     0.],
        [    0.,     0.,     0.]],

       [[  240.,     0.,     0.],
        [    0.,   800.,     0.],
        [    0.,     0.,     0.]],

       [[  300.,     0.,     0.],
        [    0.,  1000.,     0.],
        [    0.,     0.,     0.]]])

In [51]:
np.multiply(w[4], h)

array([[  300.,     0.,     0.],
       [    0.,  1000.,     0.],
       [    0.,     0.,     0.]])

In [52]:
np.sum(np.multiply(w, h), axis=(1,2))

array([  260.,   520.,   780.,  1040.,  1300.])

In [61]:
u = np.array([1,2,3,4,5])
u

array([1, 2, 3, 4, 5])

In [68]:
u = u[:, np.newaxis]
u

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [110]:
def my_convolve(x, filter_):
    """Convolution operation, assuming that stride=1, padding=0.
    """
    in_dim = x.shape[0]
    filter_size = filter_.shape[0]
    out_dim = in_dim - filter_size + 1
    feature_map = np.zeros((out_dim, out_dim))

    for i in range(out_dim):
        for j in range(out_dim):
            feature_map[i][j] = np.sum(np.multiply(x[i:i+filter_size, j:j+filter_size], filter_))
    
    return feature_map

In [111]:
x = np.zeros((5, 5))
x[2][2] = 5
x[1][1] = 3
x[4][4] = 10
x

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   3.,   0.,   0.,   0.],
       [  0.,   0.,   5.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  10.]])

In [112]:
f = np.ones((3, 3))
f[2][1] = 100
f[2][2] = 100
f

array([[   1.,    1.,    1.],
       [   1.,    1.,    1.],
       [   1.,  100.,  100.]])

In [113]:
my_convolve(x, f)

array([[  503.,   503.,     5.],
       [    8.,     8.,     5.],
       [    5.,     5.,  1005.]])

In [153]:
import numpy as np

class ConvolveOps:
    def __init__(self, x, filter_):
        self.in_dim = x.shape[0]
        self.filter_size = filter_.shape[0]
        self.out_dim = self.in_dim - self.filter_size + 1
        self.feature_map = np.zeros((self.out_dim, self.out_dim))

        self.x = x
        self.filter = filter_

    def convolve(self, optimize=True):
        """Perform convolution between the input image and the filter.
        Args:
            optimize(boolean): choose to use the optimized convolution op or not.
        """
        if optimize:
            return self._convolve_optimize()
        else:
            return self._convolve_brute_force()

    def _convolve_brute_force(self):
        """Brute force convolution operation, assuming that stride=1, padding=0."""
        for i in range(self.out_dim):
            for j in range(self.out_dim):
                self.feature_map[i][j] = np.sum(
                        np.multiply(self.x[i:i+self.filter_size, j:j+self.filter_size], 
                                    self.filter)
                        )
        
        return self.feature_map
    
    def _convolve_optimize(self):
        """Optimized convolution operation implemented matrix multiplication."""
        x_col = self._image_to_col()
        filter_row = self._filter_to_row()

        # Convolve, resulting in shape (#filters, #receptive_fields)
        self.feature_map = np.dot(filter_row, x_col)

        # Reshape the result into (out_dim, out_dim, c), no channel at this point
        self.feature_map = self.feature_map.reshape((self.out_dim, self.out_dim))

        return self.feature_map
    
    def _image_to_col(self):
        """Stretch the local regions in the input image into columns.
        Original dimension of x: (d, d)
        Stretched dimension of x: (#weights_in_a_filter, #receptive_fields)
                i.e., (filter_size * filter_size * c, out_dim * out_dim)
                where c is the number of channels
        """
        x_col = np.zeros((self.filter_size * self.filter_size, self.out_dim * self.out_dim))
        count = 0
        for i in range(self.out_dim):
            for j in range(self.out_dim):
                x_col[:, count] = self.x[i:i+self.filter_size, j:j+self.filter_size].flatten()
                count += 1
#                 print(self.x[i:i+self.filter_size, j:j+self.filter_size])
#                 print(count)
        
        return x_col
    
    def _filter_to_row(self):
        """Stretch the weights in the filter into rows.
        Original dimension of filter: (filter_size, filter_size)
        Stretched dimention of filter: (#filters, #weights_in_a_filter)
                i.e., (c, filter_size * filter_size * c)
                where c is the number of channels
        """
        # filter_row = np.zeros(self.filter_size * self.filter_size)
        filter_row = self.filter.flatten()

        return filter_row[np.newaxis, :]  

In [154]:
c = ConvolveOps(x, f)

In [155]:
c.convolve(False)

array([[  503.,   503.,     5.],
       [    8.,     8.,     5.],
       [    5.,     5.,  1005.]])

In [151]:
c._image_to_col()

array([[  0.,   0.,   0.,   0.,   3.,   0.,   0.,   0.,   5.],
       [  0.,   0.,   0.,   3.,   0.,   0.,   0.,   5.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   0.,   0.],
       [  0.,   3.,   0.,   0.,   0.,   5.,   0.,   0.,   0.],
       [  3.,   0.,   0.,   0.,   5.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   5.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   5.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   5.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  5.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.]])

In [130]:
x

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   3.,   0.,   0.,   0.],
       [  0.,   0.,   5.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  10.]])

In [156]:
c.convolve(True)

array([[  503.,   503.,     5.],
       [    8.,     8.,     5.],
       [    5.,     5.,  1005.]])

In [157]:
x

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   3.,   0.,   0.,   0.],
       [  0.,   0.,   5.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  10.]])

In [161]:
c = 3
x_stack = np.zeros((5, 5, c))  # 3 channels
x_stack[:, :, 0] = x
x_stack[:, :, 1] = x
x_stack[:, :, 2] = x
x_stack.shape

(5, 5, 3)

In [170]:
x = x_stack[0:3, 0:3, :]
x

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.]]])

In [166]:
x_stack[0:3, 0:3, :].T.flatten()

array([ 0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,
        3.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  5.])

In [171]:
x_stack

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  3.,   3.,   3.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  5.,   5.,   5.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 10.,  10.,  10.]]])

In [169]:
import numpy as np

class ConvolveOps:
    def __init__(self, x, filter_):
        self.in_dim = x.shape[0]
        self.filter_size = filter_.shape[0]
        self.c = filter_.shape[2]
        self.out_dim = self.in_dim - self.filter_size + 1

        self.feature_map = np.zeros((self.out_dim, self.out_dim, self.c))

        self.x = x
        self.filter = filter_

    def convolve(self, optimize=True):
        """Perform convolution between the input image and the filter.
        Args:
            optimize(boolean): choose to use the optimized convolution op or not.
            the brute force operation can be used for debugging.
        """
        if optimize:
            return self._convolve_optimize()
        else:
            return self._convolve_brute_force()

    def _convolve_brute_force(self):
        """Brute force convolution operation, assuming that stride=1, padding=0."""
        for depth_slice in range(self.c):
            for i in range(self.out_dim):
                for j in range(self.out_dim):
                    self.feature_map[i][j][depth_slice] = np.sum(
                                np.multiply(self.x[i:i+self.filter_size, j:j+self.filter_size], 
                                            self.filter[:, :, depth_slice])
                                )
        
        return self.feature_map
    
    def _convolve_optimize(self):
        """Optimized convolution operation using matrix multiplication.
        Achieved a speedup of ~10 times.
        """
        x_col = self._image_to_col()
        filter_row = self._filter_to_row()

        # Convolve, resulting in shape (#filters, #receptive_fields)
        self.feature_map = np.dot(filter_row, x_col)

        # Reshape the result into (out_dim, out_dim, c), no channel at this point
        self.feature_map = self.feature_map.reshape((self.out_dim, self.out_dim, self.c))

        return self.feature_map
    
    def _image_to_col(self):
        """Stretch the local regions in the input image into columns.
        Original dimension of x: (d, d)
        Stretched dimension of x: (#weights_in_one_filter, #receptive_fields)
                i.e., (filter_size * filter_size, out_dim * out_dim)
                where c is the number of channels
        """
        x_col = np.zeros((self.filter_size * self.filter_size, 
                          self.out_dim * self.out_dim))
        index = 0
        for i in range(self.out_dim):
            for j in range(self.out_dim):
                x_col[:, index] = self.x[i:i+self.filter_size, j:j+self.filter_size].flatten()
                index += 1

        return x_col
    
    def _filter_to_row(self):
        """Stretch the weights in the filter into rows.
        Original dimension of filter: (filter_size, filter_size)
        Stretched dimention of filter: (#filters, #weights_in_one_filter)
                i.e., (c, filter_size * filter_size)
                where c is the number of channels
        """
        filter_row = np.zeros((self.c, self.filter_size * self.filter_size))
        for i in range(self.c):
            filter_row[i] = self.filter[:, :, i].T.flatten()
        
        return filter_row

In [173]:
f = x
f

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.]]])

In [180]:
f[:, :, 0]

array([[ 0.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0.,  5.]])

In [175]:
x = np.zeros((5, 5))
x[0][0] = 100
x[2][3] = 200
x[4][4] = 300
x[1][1] = 50
x[3][2] = 60
x

array([[ 100.,    0.,    0.,    0.,    0.],
       [   0.,   50.,    0.,    0.,    0.],
       [   0.,    0.,    0.,  200.,    0.],
       [   0.,    0.,   60.,    0.,    0.],
       [   0.,    0.,    0.,    0.,  300.]])

In [182]:
c = ConvolveOps(x, f)

In [184]:
res1 = c.convolve(optimize=False)
res1

array([[[  150.,   150.,   150.],
        [ 1000.,  1000.,  1000.],
        [    0.,     0.,     0.]],

       [[  300.,   300.,   300.],
        [    0.,     0.,     0.],
        [  600.,   600.,   600.]],

       [[    0.,     0.,     0.],
        [  180.,   180.,   180.],
        [ 1500.,  1500.,  1500.]]])

In [185]:
res1[:, :, 0]

array([[  150.,  1000.,     0.],
       [  300.,     0.,   600.],
       [    0.,   180.,  1500.]])

In [199]:
temp = np.dot(c._filter_to_row(), c._image_to_col())
temp

array([[  150.,  1000.,     0.,   300.,     0.,   600.,     0.,   180.,
         1500.],
       [  150.,  1000.,     0.,   300.,     0.,   600.,     0.,   180.,
         1500.],
       [  150.,  1000.,     0.,   300.,     0.,   600.,     0.,   180.,
         1500.]])

In [201]:
temp.T.reshape(3, 3, 3)

array([[[  150.,   150.,   150.],
        [ 1000.,  1000.,  1000.],
        [    0.,     0.,     0.]],

       [[  300.,   300.,   300.],
        [    0.,     0.,     0.],
        [  600.,   600.,   600.]],

       [[    0.,     0.,     0.],
        [  180.,   180.,   180.],
        [ 1500.,  1500.,  1500.]]])