In [7]:
import numpy as np
import h5py
data_hf = h5py.File('/Users/ziyu/Desktop/Study Affairs/2018-Fall/cs598-deep-learning/homework/hw1/data/MNISTdata.hdf5', 'r')

In [9]:
data_hf

<HDF5 file "MNISTdata.hdf5" (mode r)>

In [12]:
list(data_hf.keys())

['x_test', 'x_train', 'y_test', 'y_train']

In [20]:
np.array(data_hf['x_train'])

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [27]:
np.array(data_hf['y_train'][:, 0])

array([5, 0, 4, ..., 5, 6, 8], dtype=int32)

In [22]:
a = np.array([1,2,3])

In [26]:
np.shape(a)

(3,)

In [28]:
data_hf['x_test']

<HDF5 dataset "x_test": shape (10000, 784), type "<f4">

In [29]:
data_hf['y_test']

<HDF5 dataset "y_test": shape (10000, 1), type "<i4">

In [30]:
np.random.randn(3)

array([ 0.82519937,  0.16057683,  0.19091626])

In [32]:
w = np.zeros([3, 2])
w

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [37]:
x = [1,2]
np.matmul(w, x)

array([ 0.,  0.,  0.])

In [80]:
a = np.array([-1, 2, -5, 10])
a

array([-1,  2, -5, 10])

In [81]:
a[a > 0] = 1

In [82]:
a

array([-1,  1, -5,  1])

In [83]:
a[a < 0] = 0

In [84]:
a

array([0, 1, 0, 1])

In [42]:
a.shape[0]

4

In [46]:
a = np.array([1,2,3,4])
b = np.array([5,6,7])

In [49]:
b[:, np.newaxis]

array([[5],
       [6],
       [7]])

In [57]:
c = np.matmul(a[:, np.newaxis], b[np.newaxis, :])

In [58]:
c

array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21],
       [20, 24, 28]])

In [61]:
c - 0.1 * c

array([[  4.5,   5.4,   6.3],
       [  9. ,  10.8,  12.6],
       [ 13.5,  16.2,  18.9],
       [ 18. ,  21.6,  25.2]])

In [62]:
c[0]

array([5, 6, 7])

In [64]:
np.array(data_hf['y_test'])

array([[7],
       [2],
       [1],
       ..., 
       [4],
       [5],
       [6]], dtype=int32)

In [66]:
np.matmul(c, np.array([1,2,3]))

array([ 38,  76, 114, 152])

In [69]:
c

array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21],
       [20, 24, 28]])